**Task 1:** 
- Import the `numpy` library and check its version.


In [1]:
import numpy as np
print(np.__version__)

2.1.1


### **Creating a NumPy Array:**

NumPy arrays are a powerful way to store and process large datasets. In this section, you will learn to create arrays.

**Task 2:**
- Create a 1D NumPy array from a Python list of numbers: `[1, 2, 3, 4, 5]`.
- Create a 2D NumPy array of shape (3x3) using the numbers from 1 to 9.
- Generate an array of 10 evenly spaced values between 0 and 5

In [2]:
array = np.array([1,2,3,4,5])
print(array.dtype)
print(array)

int64
[1 2 3 4 5]


In [3]:
import random
array = np.random.randint(low = 0 , high =10 , size = (3,3))
print(array)

[[2 2 0]
 [8 2 7]
 [3 1 4]]


In [4]:
array = np.linspace(start = 0 , stop = 6 , num = 10)
print(array)

[0.         0.66666667 1.33333333 2.         2.66666667 3.33333333
 4.         4.66666667 5.33333333 6.        ]


### **Indexing and Slicing Arrays:**

Indexing and slicing allow you to access and modify specific elements of an array.

**Task 3:**
- Access the element in the second row, third column of the 2D array you created above.
- Slice the first two rows and the first two columns from the same array.
- Modify the value in the last row and first column to 100

In [5]:
array = np.random.randint(low = 10 , high = 50 , size = (3,3))
print(array)
print(array[1,2])


[[14 36 13]
 [17 21 44]
 [32 42 10]]
44


In [6]:
print(array[0:2, 0:2])

[[14 36]
 [17 21]]


In [7]:
array[2: , 0:1] = 100
print(array)

[[ 14  36  13]
 [ 17  21  44]
 [100  42  10]]


Perform operations such as addition, subtraction, multiplication, and matrix multiplication on arrays.

**Task 5:**
- Add 5 to every element in the 1D array.
- Multiply the 2D array by 3.
- Perform matrix multiplication between the following two arrays:  
    ```python
    A = np.array([[1, 2], [3, 4]])
    B = np.array([[5, 6], [7, 8]])

In [8]:
array = np.array([1,2,3,4,5])
print(array + 5)

[ 6  7  8  9 10]


In [9]:
array = np.array([[2,4,6,8,10],[2,4,6,8,10]])
print(array * 3 )

[[ 6 12 18 24 30]
 [ 6 12 18 24 30]]


In [10]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print(np.dot(A,B))

[[19 22]
 [43 50]]


### **Understanding Broadcasting**

Broadcasting allows NumPy to work with arrays of different shapes during arithmetic operations.

**Task 6:**
- Create a 3x3 matrix of ones and a 1D array of length 3.
- Add the 1D array to each row of the matrix using broadcasting.

In [11]:
array1 = np.ones(3)
print(array1)

[1. 1. 1.]


In [12]:
array2 = np.array([1,2,3])
print(np.add(array1,array2))

[2. 3. 4.]
